# Generated by Django 3.0.5 on 2020-04-25 17:17

from django.db import migrations
from generator.movie_import import filmweb


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_movie_movie_id'),
    ]

    operations = [
        migrations.RunPython(filmweb)
    ]
