# Generated by Django 3.0.5 on 2020-04-25 17:22

from django.db import migrations
from generator.movie_import import filmweb


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20200425_1917'),
    ]

    operations = [
        migrations.RunPython(filmweb),
    ]
