# Generated by Django 3.0.5 on 2020-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_auto_20200425_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_alt',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_country',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_world',
            field=models.DateField(default=None, null=True),
        ),
    ]
