# Generated by Django 3.0.5 on 2020-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20200425_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_world',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
